import requests
from bs4 import BeautifulSoup
import smtplib
import os

amazon_url = 'https://www.amazon.com/Carhartt-Mens-NWP-M-Brown-Tanned/dp/B00TR3KZF6/ref=sr_1_1_sspa?crid=JYMRM6EUX8O5&keywords=shoe&qid=1660004137&sprefix=sh%2Caps%2C366&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzU1Q0WDJaRUI3NzI0JmVuY3J5cHRlZElkPUEwNjcxNzYyMTczNEsyWTNHMzNVVyZlbmNyeXB0ZWRBZElkPUEwODEzOTAxMjhPTEI4UVoyTDg2ViZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU='
amazon_headers = {
    'Accept-Language': 'en-US;q=0.9',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36'
}
amazon_response = requests.get(url = amazon_url, headers = amazon_headers)
amazon_response.raise_for_status()
amazon_data = amazon_response.text
amazon_soup = BeautifulSoup(amazon_data, 'html.parser')
amazon_current_price_string = amazon_soup.select('.a-offscreen')[0].string
amazon_current_price = float(amazon_current_price_string[1:])

camel_url = 'https://camelcamelcamel.com/product/B00TR3KZF6'

camel_response = requests.get(url = camel_url)
camel_response.raise_for_status()
camel_data = camel_response.text
camel_soup = BeautifulSoup(camel_data, 'html.parser')
camel_average_price = float(camel_soup.select('.product_pane tr')[4].select('td')[1].string[1:])


if(camel_average_price >= amazon_current_price):
    port = 587
    SMTP_SERVER = os.environ['SMTP_SERVER']
    EMAIL = os.environ['EMAIL']
    PASSWORD = os.environ['PASSWORD'] # your password generated by Mailtrap
    TO = os.environ['TO']
    with smtplib.SMTP(SMTP_SERVER, port=587) as connection:
        connection.starttls()
        result = connection.login(EMAIL, PASSWORD)
        connection.sendmail(
            from_addr=EMAIL,
            to_addrs=TO,
            msg=f"Subject:Amazon Price Alert!\n\nYour shoes are on sale {amazon_current_price}\n{amazon_url}"
        )




